services:
  database-service:
    image: postgres:latest
    container_name: db_psql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    expose:
      - 5433
    volumes:
      - dbpsql:/var/lib/postgresql/data
      - ./dbbackup:/dbbackup
      - ./zabbix-agent/dbinit:/docker-entrypoint-initdb.d
    networks:
      - db-network

  db-psql-zabbix-agent:
    image: zabbix/zabbix-agent2:latest
    container_name: db_psql_zabbix_agent
    environment:
      ZBX_HOSTNAME: "db_psql"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    depends_on:
      - zabbix-server
      - database-service
    networks:
      - db-network
      - zabbix-network
    restart: unless-stopped

  admin-panel-service:
    image: adminer
    container_name: db_admin_panel
    depends_on:
      - database-service
    ports:
      - 8050:8080
    expose:
      - 8050
    networks:
      - db-network
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: db_psql

networks:
  db-network:
  zabbix-network:
volumes:
  dbpsql:
  dbbackup: