services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    ports:
      - "10051:10051"
    depends_on:
      - zabbix-db
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-db:
    image: postgres:latest
    container_name: zabbix-db
    environment:
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
    volumes:
      - zabbixpsql:/var/lib/postgresql/data
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    container_name: zabbix-agent
    environment:
      ZBX_HOSTNAME: "zabbix-server"
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: '10051'
      ZBX_SERVER_ACTIVE: zabbix-server
    depends_on:
      - zabbix-server
    privileged: true
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    ports:
      - "8051:8080"
    expose:
      - 8051
    depends_on:
      - zabbix-server
      - zabbix-db
    environment:
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: ${ZABBIX_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ZABBIX_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ZABBIX_POSTGRES_DB}
      PHP_TZ: Europe/Warsaw
    networks:
      - zabbix-network
    restart: unless-stopped

networks:
  zabbix-network:
volumes:
  zabbixpsql: