
services:
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_URI: db_psql:5432?sslmode=disable
      DATA_SOURCE_USER: ${POSTGRES_EXPORTER_USER}
      DATA_SOURCE_PASSWORD: ${POSTGRES_EXPORTER_PASSWORD}
      DATA_SOURCE_NAME: ${POSTGRES_DB}
    ports:
      - "9187:9187"
    networks:
      - db-network
      - monitoring-network
    depends_on:
      - database-service
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/conf:/etc/prometheus/
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
    depends_on:
      - postgres-exporter
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: your_grafana_password
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/conf/provisioning:/etc/grafana/provisioning/
    networks:
      - monitoring-network
    depends_on:
      - prometheus
    restart: unless-stopped

networks:
  monitoring-network:

volumes:
  prometheus_data:
  grafana_data: