
services:
  database-backup:
    image: postgres:latest
    container_name: database-backup
    environment:
      HOST: db_psql
      PORT: 5432
      USER: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
      DB: ${POSTGRES_DB}
      BACKUP_DIR: /dbbackup/backups
    volumes:
     - ./dbbackup/:/dbbackup/
    networks:
      - db-network
    depends_on:
      - database-service
    #backup data when starting service
    entrypoint: ./dbbackup/backup.sh
